### ISSUE TITLE
Please update a README file for better understanding of this project

### ISSUE THREAD

**Issue by GeekyShiva** [falcon1996/Twitter-Sentiment-Analysis#1]
Hi @falcon1996 , it's nice you uploaded an awesome project.

I would recommend to upload a README file which contains the following details about your project:
- Development Pedagogy used
- File system and details of the files.
- Dependencies
- Working Screenshots are a bonus

I found a readme.pdf file at  ` Twitter-Sentiment-Analysis/sanders-twitter-0.2/readme.pdf ` path and that contains the major baseplate details. Please put file upfront.

Hope this helps :)

**Comment by falcon1996** [comment]
Hey, @GeekyShiva thanks for the feedback, will work on the suggested changes ASAP.
